import {test} from 'node:test';
import assert from 'node:assert/strict';
import {SPACE_COURSE,createSpaceGame,startSpace,pauseSpace,shiftSpace,advanceSpace} from '../src/space-game.js';
test('one bounded course with adjacent safe routes and readable gate spacing',()=>{let lane=1;assert.equal(SPACE_COURSE.gates.length,18);for(const gate of SPACE_COURSE.gates){assert.equal(Math.abs(gate.safeLane-lane),1);assert(!gate.blocked.includes(gate.safeLane));lane=gate.safeLane;}assert(SPACE_COURSE.gates[0].distance/SPACE_COURSE.speed>3);assert((SPACE_COURSE.gates[1].distance-SPACE_COURSE.gates[0].distance)/SPACE_COURSE.speed>1.5);});
for(const fps of [20,30,60,120])test(`Space Run completes with one timely shift per gate at ${fps}fps`,()=>{const g=createSpaceGame();startSpace(g);let gate=0;for(let frame=0;frame<10000&&g.phase==='running';frame++){if(gate<g.course.gates.length&&g.distance>=g.course.gates[gate].distance-5){assert(shiftSpace(g));gate++;}advanceSpace(g,1/fps);}assert.equal(g.phase,'won');assert.equal(g.collected.size,18);assert.equal(g.passed.size,18);assert.equal(g.score,270);});
test('Space Run collision cannot be skipped by long frame',()=>{const g=createSpaceGame();startSpace(g);g.distance=g.course.gates[0].distance-1.5;advanceSpace(g,1);assert.equal(g.phase,'lost');});
test('Space Run pause freezes forward movement and shift',()=>{const g=createSpaceGame();startSpace(g);shiftSpace(g);advanceSpace(g,.04);pauseSpace(g);const x=g.x,d=g.distance;advanceSpace(g,.25);assert.equal(g.x,x);assert.equal(g.distance,d);assert.equal(shiftSpace(g),false);startSpace(g);advanceSpace(g,.25);assert(g.distance>d);});
test('steering is adjacent, bounded and repeat-safe',()=>{const g=createSpaceGame();startSpace(g);assert(shiftSpace(g,-1));assert.equal(shiftSpace(g,-1),false);advanceSpace(g,.25);assert.equal(g.lane,0);assert.equal(shiftSpace(g,-1),false);assert(shiftSpace(g,1));advanceSpace(g,.25);assert.equal(g.lane,1);});
test('Space Run retry resets every course resource',()=>{const g=createSpaceGame();assert.equal(g.phase,'ready');assert.equal(g.distance,0);assert.equal(g.score,0);assert.equal(g.collected.size,0);assert.equal(g.passed.size,0);});
